spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:dogdata

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: true

graphiql:
  enabled: true
  endpoint: /graphql
  mapping: /graphiql
